### ISSUE TITLE
How to use ActivitiesZones?

### ISSUE THREAD

**Issue by trijerett** [mpclarkson/StravaSwift#18]
Looking to use the ActivitiesZones that is in the Router.swift file.  How would I go about using it to request/get time spent in different zones (power, heart rate, pace).  Thanks!

**Comment by lludo** [comment]
Get Activity Zones returns the zones for a given activity id.
http://developers.strava.com/docs/reference/#api-Activities-getZonesByActivityId

**Comment by lludo** [comment]
Closing this for now as it does not look to be a SDK related issue.
