### ISSUE TITLE
Support for Alamofire 4.0

### ISSUE THREAD

**Issue by danieltigse** [mpclarkson/StravaSwift#6]
I have this error:

[!] Unable to satisfy the following requirements:

- `Alamofire (~> 3.1)` required by `StravaSwift (0.1.0)`

**Comment by agonzalezjr** [comment]
This is because the version in CocoaPods is only 0.5.0, and the latest (0.6.0) hasn't been deployed yet. While that is fixed, you could clone the repo and get the latest source. It will support Swift 3 and that will use Alamofile ~> 4 😉

**Comment by mpclarkson** [comment]
I have updated cocoa pods to the 0.7.0 tag. Please confirm it's working now!

**Comment by lludo** [comment]
This is currently working with Alamofire 4.x (We will now have to think about migrating to 5.x once the final version is released).
