### ISSUE TITLE
Example for athletesStats please

### ISSUE THREAD

**Issue by danieltigse** [mpclarkson/StravaSwift#7]

**Comment by agonzalezjr** [comment]
I am playing with the Example app, and I could add this. 
Is there something you are looking for in particular?

**Comment by danieltigse** [comment]
No. Just an example for this. The library include the method to fetch the statistics but not an example.

**Comment by agonzalezjr** [comment]
Just submitted a PR for this.
Check out the new `AthleteStats.swift` class for the example you are looking for.

**Comment by mpclarkson** [comment]
Hey thanks for this. I'll merge it now. Sorry, I haven't been around much - been preoccupied with other things!
